# Generated by Django 5.1.4 on 2024-12-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarakonsh',
            name='test_image',
            field=models.ImageField(default=None, upload_to='../media/'),
            preserve_default=False,
        ),
    ]
