# Generated by Django 5.1.4 on 2024-12-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_tarakonsh_test_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarakonsh',
            name='test_image',
            field=models.ImageField(null=True, upload_to='../media/'),
        ),
    ]
