# Generated by Django 5.1.4 on 2024-12-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_tarakonsh_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarakonsh',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
